# IEI Base Dockerfile for Py modules
ARG UBUNTU_IMAGE_VERSION
ARG IEI_VERSION

FROM quay.io/coreos/etcd:v3.0.16
RUN chmod +x /usr/local/bin/etcd
ENTRYPOINT ["/usr/local/bin/etcd", "-advertise-client-urls", "https://0.0.0.0:2379", "-listen-client-urls", "https://0.0.0.0:2379", "--cert-file", "/run/secrets/etcd.server.cert", "--key-file", "/run/secrets/etcd.server.key", "--client-cert-auth", "--trusted-ca-file", "/run/secrets/etcd.ca.cert"]