# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dainternal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dainternal.proto',
  package='DataAgentInternal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x64\x61internal.proto\x12\x11\x44\x61taAgentInternal\"\x1f\n\x0c\x43onfigIntReq\x12\x0f\n\x07\x63\x66gType\x18\x01 \x01(\t\" \n\rConfigIntResp\x12\x0f\n\x07jsonMsg\x18\x01 \x01(\t2a\n\ndainternal\x12S\n\x0cGetConfigInt\x12\x1f.DataAgentInternal.ConfigIntReq\x1a .DataAgentInternal.ConfigIntResp\"\x00\x62\x06proto3')
)




_CONFIGINTREQ = _descriptor.Descriptor(
  name='ConfigIntReq',
  full_name='DataAgentInternal.ConfigIntReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfgType', full_name='DataAgentInternal.ConfigIntReq.cfgType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=70,
)


_CONFIGINTRESP = _descriptor.Descriptor(
  name='ConfigIntResp',
  full_name='DataAgentInternal.ConfigIntResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonMsg', full_name='DataAgentInternal.ConfigIntResp.jsonMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ConfigIntReq'] = _CONFIGINTREQ
DESCRIPTOR.message_types_by_name['ConfigIntResp'] = _CONFIGINTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigIntReq = _reflection.GeneratedProtocolMessageType('ConfigIntReq', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGINTREQ,
  __module__ = 'dainternal_pb2'
  # @@protoc_insertion_point(class_scope:DataAgentInternal.ConfigIntReq)
  ))
_sym_db.RegisterMessage(ConfigIntReq)

ConfigIntResp = _reflection.GeneratedProtocolMessageType('ConfigIntResp', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGINTRESP,
  __module__ = 'dainternal_pb2'
  # @@protoc_insertion_point(class_scope:DataAgentInternal.ConfigIntResp)
  ))
_sym_db.RegisterMessage(ConfigIntResp)



_DAINTERNAL = _descriptor.ServiceDescriptor(
  name='dainternal',
  full_name='DataAgentInternal.dainternal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=203,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConfigInt',
    full_name='DataAgentInternal.dainternal.GetConfigInt',
    index=0,
    containing_service=None,
    input_type=_CONFIGINTREQ,
    output_type=_CONFIGINTRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAINTERNAL)

DESCRIPTOR.services_by_name['dainternal'] = _DAINTERNAL

# @@protoc_insertion_point(module_scope)
