# dockerfile for DataAgent
FROM ubuntu:16.04
LABEL version="1.0"
LABEL description="DataAgent image"

ENV DIR /ETA
WORKDIR ${DIR}

RUN mkdir -p log
# Adding DataAgent binary
ADD da ./DataAgent

ENTRYPOINT ./DataAgent -config=./DataAgent.conf -log_dir=${DIR}/log/DataAgent