# Redis dockerfile
ARG REDIS_VERSION
FROM redis:$REDIS_VERSION

ARG HOST_TIME_ZONE=""

# Setting timezone inside the container
RUN echo "$HOST_TIME_ZONE" >/etc/timezone 
RUN cat /etc/timezone
RUN ln -sf /usr/share/zoneinfo/${HOST_TIME_ZONE} /etc/localtime 
RUN dpkg-reconfigure -f noninteractive tzdata