# Dockerfile for DataAgent
FROM ia/gobase:1.0
LABEL version="1.0"
LABEL description="DataAgent image"

ADD DataAgent ./DataAgent
ADD StreamManager ./StreamManager
ADD Util ./Util

ADD Gopkg.toml ./
ADD Gopkg.lock ./

RUN mkdir -p ${DIR}/log && \
    dep ensure -vendor-only -v && \
    go build -o /root/go/bin/DataAgent DataAgent/DataAgent.go

ENTRYPOINT ["DataAgent", "-config=DataAgent/DataAgent.conf", "-log_dir=${DIR}/log/DataAgent"]