# dockerfile for NATS client
FROM ia/pybase:1.0
LABEL version="1.0"
LABEL description="NATS python client image"

# Adding NATS python files
ADD StreamManager/test/natsClient.py . 

# Installing nats library
RUN pip3.6 install asyncio-nats-client

ENTRYPOINT ["python3.6", "natsClient.py"]
CMD ["classifier_results"]