loadGlobalLibrary()

pipeline {
    agent { label 'EIS_Pipeline' }
    parameters {
        string(name: 'SCANNERS', defaultValue: 'protex,checkmarx,bdba', description: 'Valid scanners are protex, checkmarx, bdba')
        string(name: 'CI_TESTS_BRANCH', defaultValue: 'master', description: 'CITests branch to clone')
        string(name: 'PROTEX_PROJECT_NAME', defaultValue: 'Edge Insights Software v2.3', description: 'Protex Project Name')
        string(name: 'CHECKMARX_PROJECT_NAME', defaultValue: 'IEI_CI_Checkmarx', description: 'Protex Project Name')
        booleanParam defaultValue: true, description: 'Execute Fresh build', name: 'CLEAN_BUILD'
    }
    options {
        gitLabConnection('BuildAutomation')
        gitlabBuilds(builds: ['Build', 'Klocwork', 'Prep Static Code Scan', 'Static Code Analysis', 'Virus Scan', 'Notify'])
        buildDiscarder(logRotator(numToKeepStr: '30', daysToKeepStr: '30'))
        timestamps()
        disableConcurrentBuilds()
        timeout(time: 9, unit: 'HOURS')
        skipDefaultCheckout() // manual checkout stage to allow for a clean workspace on each build
    }
    triggers {
        cron('@daily')
    }
    environment {
        PASSWORD = credentials('eis-strong-password')
        STATIC_RESOURCES = "/home/$USER/openvino_sdk"
        OPENVINO_VERSION = "2020.1.023"
        PROTECODE_BIN_DIR = "Protecode"
        EMAIL_ARTIFACTS_DIR = getTmpDir()
    }
    stages {
        stage('Build') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            steps {
                cleanWs()
                checkout scm

                // Enable all services in build/docker-compose.yml
                echo "Uncomment all services in build/docker-compose.yml file..."
                sh 'sed -i "s:^  # :  :g" build/docker-compose.yml'

                dir('CITests') {
                    git url: 'ssh://git@gitlab.devtools.intel.com:29418/Indu/IEdgeInsights/CITests.git', branch: "${params.CI_TESTS_BRANCH}", changelog: false, poll: false

                    sh 'echo $PASSWORD | sudo -SEH pip3 install -r requirements.txt'

                    script {
                        def envVars = []

                        if(env.CLEAN_BUILD == 'true') {
                            envVars << "BUILD_TYPE=nightly"
                        }

                        withEnv(envVars) {
                            sh 'echo $PASSWORD | sudo -SE python3 pre_merge_and_nightly_build_script.py'
                        }

                        sh 'docker ps -a' //debug

                        // Copy binaries from inside docker containers to the protecode directory
                        sh 'rm -rf $PROTECODE_BIN_DIR && mkdir -p $PROTECODE_BIN_DIR'

                        sh 'docker cp -a ia_video_ingestion:/EIS/go/src/IEdgeInsights/VideoIngestion/build/video-ingestion $PROTECODE_BIN_DIR/video-ingestion'
                        sh 'docker cp -a ia_video_analytics:/EIS/go/src/IEdgeInsights/VideoAnalytics/build/video-analytics $PROTECODE_BIN_DIR/video-analytics'
                        sh 'docker cp -a ia_imagestore:/EIS/go/src/IEdgeInsights/ImageStore/main $PROTECODE_BIN_DIR/imagestore_main'
                        sh 'docker cp -a ia_influxdbconnector:/EIS/go/bin/InfluxDBConnector $PROTECODE_BIN_DIR/InfluxDBConnector'
                        sh 'docker cp -a ia_opcua_export:/EIS/go/src/IEdgeInsights/OpcuaExport/OpcuaExport $PROTECODE_BIN_DIR/OpcuaExport'
                        sh 'docker cp -a ia_rest_export:/EIS/go/src/IEdgeInsights/RestDataExport/RestDataExport $PROTECODE_BIN_DIR/RestDataExport'

                        stash name: 'bdba', includes: "${PROTECODE_BIN_DIR}/**"
                    }
                }

                updateGitlabCommitStatus name: env.STAGE_NAME, state: 'success'
            }
        }

        stage('Klocwork') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            environment {
                STATIC_RESOURCES = "/home/$USER/openvino_sdk"
                OPENVINO_VERSION = "2020.1.023"
                PROJECT_NAME     = 'FoG_ETA'
                TABLE_ROOT       = "/home/$USER/kw/FG_Table"
                KW_SERVER        = 'https://klocwork-ir1.devtools.intel.com:8075'
                KW_HOST          = 'klocwork02p.elic.intel.com'
                KW_PORT          = '7500'
                PATH             = "$PATH:/home/$USER/kw/kw18/bin:/usr/local/go/bin"
                GOPATH           = "$WORKSPACE"
                RBHE_DOCKER      = credentials('intel-harbor-credentials')
            }
            steps {
                // modeled after https://jenkins-iotg-val-ba.iind.intel.com/view/EIS/job/EIS_CI_NIGHTLY_Docker_KW
                cleanWs()


                withCredentials([usernamePassword(credentialsId: 'eis-kw', usernameVariable: 'KW_USER', passwordVariable: 'KW_PWD')]) {
                    // available as an env variable, but will be masked if you try to print it out any which way
                    // note: single quotes prevent Groovy interpolation; expansion is by Bourne Shell, which is what you want
                    sh '''
                    echo $KW_USER > kwcreds
                    echo $KW_PWD >> kwcreds
                    '''
                }

                sh '''
                echo $PASSWORD | sudo -S chmod -R 777 docker_setup/provision
                cp -r CITests/klocwork/. .
                # Build klockwork image
                docker-compose build

                rm -rf kwcreds

                # Run KW scan
                docker-compose up -d

                # print logs
                docker logs -f ia_klocwork

                exit_code=`docker inspect ia_klocwork --format='{{.State.ExitCode}}'`
                if [ "$exit_code" != 0 ]; then
                    exit -1
                fi
                '''

                // generate KW report and archive
                script {
                    sh 'docker login --username="$RBHE_DOCKER_USR" --password="$RBHE_DOCKER_PSW" amr-registry.caas.intel.com'
                    sh 'docker pull amr-registry.caas.intel.com/rrp-devops/klocwork-report-agent:latest'

                    def kwReportImage = 'amr-registry.caas.intel.com/rrp-devops/klocwork-report-agent:latest'

                    docker.image(kwReportImage).inside('-v /home/labuser/.klocwork:/tmp/.klocwork -e http_proxy= -e https_proxy=') {
                        withEnv(['KLOCWORK_LTOKEN=/tmp/.klocwork/ltoken']) {
                            sh '''
                            mkdir -p klocwork-reports
                            python /klocwork/OWR_klocwork_report.py -s "https://irvapp007.ir.intel.com" -p "8075" -t "$PROJECT_NAME" -b default -q "$KW_REPORT_QUERY" -o klocwork-reports/kw_report.html
                            '''
                        }
                    }

                    publishHTML([
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: "klocwork-reports",
                        reportFiles: 'kw_report.html',
                        reportName: 'Klocwork Report',
                        reportTitles: 'Klocwork Report'
                    ])

                    archiveArtifacts allowEmptyArchive: true, artifacts: 'klocwork-reports/kw_report.csv'

                    sh 'mkdir -p $EMAIL_ARTIFACTS_DIR'
                    sh 'cp klocwork-reports/kw_report* $EMAIL_ARTIFACTS_DIR'
                }

                updateGitlabCommitStatus name: env.STAGE_NAME, state: 'success'
            }
        }

        stage('Prep Static Code Scan') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            steps {
                // clean static code scan parallel dirs
                sh 'echo $PASSWORD | sudo -SE sudo rm -rf ${WORKSPACE}@[2,3,4]/*'
                sh 'echo $PASSWORD | sudo -SE sudo rm -rf ${WORKSPACE}@[2,3,4]/.[^.]*'
            }
        }

        stage('Static Code Scan') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            environment {
                // SCANNERS = 'protex,checkmarx,bdba'  //see parameter above
                PROJECT_NAME = 'EIS'
                
                // PROTEX_PROJECT_NAME  = '' //see parameter above
                PROTEX_SERVER_URL    = 'https://garprotex009.devtools.intel.com/'
                PROTEX_CREDENTIAL_ID = 'protex-gar009'

                // CHECKMARX_PROJECT_NAME     = '' //see parameter above
                CHECKMARX_CREDENTIAL_ID    = 'checkmarx-scanner-credentials'
                CHECKMARX_GROUP_ID         = '0f40ed7e-d5c7-45dd-ba72-a7a3ea9d59e5'
                CHECKMARX_PRESET_ID        = '100049'
                CHECKMARX_INCREMENTAL_SCAN = 'true'
            }
            steps {
                cleanWs()

                dir('CleanSourceCode') {
                    checkout scm

                    // depends on the Build stage
                    unstash 'bdba'

                    withEnv(["WORKSPACE=${WORKSPACE}/CleanSourceCode"]) {
                        rbheStaticCodeScan()
                    }
                }

                sh 'cp ${WORKSPACE}@[2,3,4]/**/CodeOriginationScan* $EMAIL_ARTIFACTS_DIR/'
                sh 'cp ${WORKSPACE}@[2,3,4]/**/**/CxSASTReport_* $EMAIL_ARTIFACTS_DIR/'

                updateGitlabCommitStatus name: env.STAGE_NAME, state: 'success'
            }
        }

        stage('Virus Scan') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            steps {
                // The only files that need to be scanned are the compiled binaries
                // so we will just scan the bdba folder since it has the required files
                script {
                    virusScan {
                        dir = "./CleanSourceCode/Protecode"
                    }

                    sh 'cp vsreports/report.html $EMAIL_ARTIFACTS_DIR/virus-scan.html'
                    sh 'ls -al $EMAIL_ARTIFACTS_DIR'
                }

                updateGitlabCommitStatus name: env.STAGE_NAME, state: 'success'
            }
        }

        stage('Notify') {
            when {
                anyOf {
                    triggeredBy 'UserIdCause'
                    allOf {
                        triggeredBy 'TimerTrigger'
                        branch 'feature/v2.3'
                    }
                }
            }
            steps {
                sh 'rm -rf FinalReports && mkdir -p FinalReports'
                sh 'cp $EMAIL_ARTIFACTS_DIR/* FinalReports/'

                emailext(
                    body: '$DEFAULT_CONTENT',
                    replyTo: '$DEFAULT_REPLYTO',
                    subject: '$DEFAULT_SUBJECT',
                    to: env.EIS_BUILD_PDL,
                    attachmentsPattern: "FinalReports/*"
                )
            }
        }
    }
    post {
        always {
            cleanWs()
        }

        success {
            updateGitlabCommitStatus name: env.STAGE_NAME, state: 'success'
        }

        failure {
            emailext(
                body: '$DEFAULT_CONTENT',
                replyTo: '$DEFAULT_REPLYTO',
                subject: '$DEFAULT_SUBJECT',
                to: env.EIS_BUILD_PDL
            )

            updateGitlabCommitStatus name: env.STAGE_NAME, state: 'failed'
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'jenkins-common-pipelines@master',
        changelog: false,
        retriever: legacySCM([
            $class: 'GitSCM',
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            userRemoteConfigs: [[
                credentialsId: 'iotg-rbhe-github-impcloud-pat',
                url: 'https://github.impcloud.net/Responsive-Retail/jenkins-common-pipelines.git'
            ]],
            extensions: [
                [$class: 'SubmoduleOption', recursiveSubmodules: true],
                [$class: 'IgnoreNotifyCommit']
            ]
        ])
    ) _
}

def getTmpDir() {
    sh(script: 'mktemp -d -t ci-XXXXXXXXXX', returnStdout: true).trim()
}
