// Code generated by protoc-gen-go. DO NOT EDIT.
// source: da.proto

package DataAgent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message for GetConfigInt
type ConfigIntReq struct {
	CfgType              string   `protobuf:"bytes,1,opt,name=cfgType" json:"cfgType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigIntReq) Reset()         { *m = ConfigIntReq{} }
func (m *ConfigIntReq) String() string { return proto.CompactTextString(m) }
func (*ConfigIntReq) ProtoMessage()    {}
func (*ConfigIntReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{0}
}
func (m *ConfigIntReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigIntReq.Unmarshal(m, b)
}
func (m *ConfigIntReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigIntReq.Marshal(b, m, deterministic)
}
func (dst *ConfigIntReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigIntReq.Merge(dst, src)
}
func (m *ConfigIntReq) XXX_Size() int {
	return xxx_messageInfo_ConfigIntReq.Size(m)
}
func (m *ConfigIntReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigIntReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigIntReq proto.InternalMessageInfo

func (m *ConfigIntReq) GetCfgType() string {
	if m != nil {
		return m.CfgType
	}
	return ""
}

// The response message for GetConfigInt
type ConfigIntResp struct {
	JsonMsg              string   `protobuf:"bytes,1,opt,name=jsonMsg" json:"jsonMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigIntResp) Reset()         { *m = ConfigIntResp{} }
func (m *ConfigIntResp) String() string { return proto.CompactTextString(m) }
func (*ConfigIntResp) ProtoMessage()    {}
func (*ConfigIntResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{1}
}
func (m *ConfigIntResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigIntResp.Unmarshal(m, b)
}
func (m *ConfigIntResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigIntResp.Marshal(b, m, deterministic)
}
func (dst *ConfigIntResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigIntResp.Merge(dst, src)
}
func (m *ConfigIntResp) XXX_Size() int {
	return xxx_messageInfo_ConfigIntResp.Size(m)
}
func (m *ConfigIntResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigIntResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigIntResp proto.InternalMessageInfo

func (m *ConfigIntResp) GetJsonMsg() string {
	if m != nil {
		return m.JsonMsg
	}
	return ""
}

// The request message for GetQuery
type QueryReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{2}
}
func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (dst *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(dst, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

// The response message for GetQuery
type QueryResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{3}
}
func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (dst *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(dst, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

// The request message for GetConfig
type ConfigReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigReq) Reset()         { *m = ConfigReq{} }
func (m *ConfigReq) String() string { return proto.CompactTextString(m) }
func (*ConfigReq) ProtoMessage()    {}
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{4}
}
func (m *ConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigReq.Unmarshal(m, b)
}
func (m *ConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigReq.Marshal(b, m, deterministic)
}
func (dst *ConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigReq.Merge(dst, src)
}
func (m *ConfigReq) XXX_Size() int {
	return xxx_messageInfo_ConfigReq.Size(m)
}
func (m *ConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigReq proto.InternalMessageInfo

// The response message for GetConfig
type ConfigResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResp) Reset()         { *m = ConfigResp{} }
func (m *ConfigResp) String() string { return proto.CompactTextString(m) }
func (*ConfigResp) ProtoMessage()    {}
func (*ConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_f32112af9df5dcb5, []int{5}
}
func (m *ConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResp.Unmarshal(m, b)
}
func (m *ConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResp.Marshal(b, m, deterministic)
}
func (dst *ConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResp.Merge(dst, src)
}
func (m *ConfigResp) XXX_Size() int {
	return xxx_messageInfo_ConfigResp.Size(m)
}
func (m *ConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConfigIntReq)(nil), "DataAgent.ConfigIntReq")
	proto.RegisterType((*ConfigIntResp)(nil), "DataAgent.ConfigIntResp")
	proto.RegisterType((*QueryReq)(nil), "DataAgent.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "DataAgent.QueryResp")
	proto.RegisterType((*ConfigReq)(nil), "DataAgent.ConfigReq")
	proto.RegisterType((*ConfigResp)(nil), "DataAgent.ConfigResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaClient is the client API for Da service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaClient interface {
	// **********Internal Interfaces***************
	// GetConfigInt internal interface
	GetConfigInt(ctx context.Context, in *ConfigIntReq, opts ...grpc.CallOption) (*ConfigIntResp, error)
	// **********External Interfaces***************
	// GetConfig external interface
	Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error)
	// GetQuery external interface
	Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
}

type daClient struct {
	cc *grpc.ClientConn
}

func NewDaClient(cc *grpc.ClientConn) DaClient {
	return &daClient{cc}
}

func (c *daClient) GetConfigInt(ctx context.Context, in *ConfigIntReq, opts ...grpc.CallOption) (*ConfigIntResp, error) {
	out := new(ConfigIntResp)
	err := c.cc.Invoke(ctx, "/DataAgent.da/GetConfigInt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daClient) Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error) {
	out := new(ConfigResp)
	err := c.cc.Invoke(ctx, "/DataAgent.da/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daClient) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/DataAgent.da/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaServer is the server API for Da service.
type DaServer interface {
	// **********Internal Interfaces***************
	// GetConfigInt internal interface
	GetConfigInt(context.Context, *ConfigIntReq) (*ConfigIntResp, error)
	// **********External Interfaces***************
	// GetConfig external interface
	Config(context.Context, *ConfigReq) (*ConfigResp, error)
	// GetQuery external interface
	Query(context.Context, *QueryReq) (*QueryResp, error)
}

func RegisterDaServer(s *grpc.Server, srv DaServer) {
	s.RegisterService(&_Da_serviceDesc, srv)
}

func _Da_GetConfigInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigIntReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaServer).GetConfigInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataAgent.da/GetConfigInt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaServer).GetConfigInt(ctx, req.(*ConfigIntReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Da_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataAgent.da/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaServer).Config(ctx, req.(*ConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Da_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataAgent.da/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaServer).Query(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Da_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataAgent.da",
	HandlerType: (*DaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigInt",
			Handler:    _Da_GetConfigInt_Handler,
		},
		{
			MethodName: "Config",
			Handler:    _Da_Config_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Da_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "da.proto",
}

func init() { proto.RegisterFile("da.proto", fileDescriptor_da_f32112af9df5dcb5) }

var fileDescriptor_da_f32112af9df5dcb5 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x74, 0x49, 0x2c, 0x49, 0x74, 0x4c, 0x4f, 0xcd, 0x2b, 0x51,
	0xd2, 0xe0, 0xe2, 0x71, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xf7, 0xcc, 0x2b, 0x09, 0x4a, 0x2d, 0x14,
	0x92, 0xe0, 0x62, 0x4f, 0x4e, 0x4b, 0x0f, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0x71, 0x95, 0x34, 0xb9, 0x78, 0x91, 0x54, 0x16, 0x17, 0x80, 0x94, 0x66, 0x15, 0xe7,
	0xe7, 0xf9, 0x16, 0xa7, 0xc3, 0x94, 0x42, 0xb9, 0x4a, 0x5c, 0x5c, 0x1c, 0x81, 0xa5, 0xa9, 0x45,
	0x95, 0x41, 0xa9, 0x85, 0x4a, 0xdc, 0x5c, 0x9c, 0x50, 0x76, 0x71, 0x01, 0x88, 0x03, 0x31, 0x03,
	0x24, 0xc3, 0xc3, 0xc5, 0x05, 0xe3, 0x14, 0x17, 0x18, 0xed, 0x60, 0xe4, 0x62, 0x4a, 0x49, 0x14,
	0x72, 0xe6, 0xe2, 0x71, 0x4f, 0x2d, 0x81, 0x5b, 0x24, 0x24, 0xae, 0x07, 0x77, 0xab, 0x1e, 0xb2,
	0x43, 0xa5, 0x24, 0xb0, 0x4b, 0x14, 0x17, 0x28, 0x31, 0x08, 0x99, 0x73, 0xb1, 0x41, 0x84, 0x84,
	0x44, 0x30, 0x54, 0x81, 0xf4, 0x8a, 0x62, 0x11, 0x05, 0x6b, 0x34, 0xe1, 0x62, 0x05, 0x3b, 0x56,
	0x48, 0x18, 0x49, 0x05, 0xcc, 0x2b, 0x52, 0x22, 0x98, 0x82, 0x20, 0x5d, 0x49, 0x6c, 0xe0, 0x50,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x76, 0x11, 0x8a, 0x61, 0x01, 0x00, 0x00,
}
