# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: da.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='da.proto',
  package='DataAgent',
  syntax='proto3',
  serialized_pb=_b('\n\x08\x64\x61.proto\x12\tDataAgent\"\x1f\n\x0c\x43onfigIntReq\x12\x0f\n\x07\x63\x66gType\x18\x01 \x01(\t\" \n\rConfigIntResp\x12\x0f\n\x07jsonMsg\x18\x01 \x01(\t\"\n\n\x08QueryReq\"\x0b\n\tQueryResp\"\x0b\n\tConfigReq\"\x0c\n\nConfigResp2\xb8\x01\n\x02\x64\x61\x12\x43\n\x0cGetConfigInt\x12\x17.DataAgent.ConfigIntReq\x1a\x18.DataAgent.ConfigIntResp\"\x00\x12\x37\n\x06\x43onfig\x12\x14.DataAgent.ConfigReq\x1a\x15.DataAgent.ConfigResp\"\x00\x12\x34\n\x05Query\x12\x13.DataAgent.QueryReq\x1a\x14.DataAgent.QueryResp\"\x00\x62\x06proto3')
)




_CONFIGINTREQ = _descriptor.Descriptor(
  name='ConfigIntReq',
  full_name='DataAgent.ConfigIntReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cfgType', full_name='DataAgent.ConfigIntReq.cfgType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=54,
)


_CONFIGINTRESP = _descriptor.Descriptor(
  name='ConfigIntResp',
  full_name='DataAgent.ConfigIntResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonMsg', full_name='DataAgent.ConfigIntResp.jsonMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=88,
)


_QUERYREQ = _descriptor.Descriptor(
  name='QueryReq',
  full_name='DataAgent.QueryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=100,
)


_QUERYRESP = _descriptor.Descriptor(
  name='QueryResp',
  full_name='DataAgent.QueryResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=113,
)


_CONFIGREQ = _descriptor.Descriptor(
  name='ConfigReq',
  full_name='DataAgent.ConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=126,
)


_CONFIGRESP = _descriptor.Descriptor(
  name='ConfigResp',
  full_name='DataAgent.ConfigResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['ConfigIntReq'] = _CONFIGINTREQ
DESCRIPTOR.message_types_by_name['ConfigIntResp'] = _CONFIGINTRESP
DESCRIPTOR.message_types_by_name['QueryReq'] = _QUERYREQ
DESCRIPTOR.message_types_by_name['QueryResp'] = _QUERYRESP
DESCRIPTOR.message_types_by_name['ConfigReq'] = _CONFIGREQ
DESCRIPTOR.message_types_by_name['ConfigResp'] = _CONFIGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigIntReq = _reflection.GeneratedProtocolMessageType('ConfigIntReq', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGINTREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigIntReq)
  ))
_sym_db.RegisterMessage(ConfigIntReq)

ConfigIntResp = _reflection.GeneratedProtocolMessageType('ConfigIntResp', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGINTRESP,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigIntResp)
  ))
_sym_db.RegisterMessage(ConfigIntResp)

QueryReq = _reflection.GeneratedProtocolMessageType('QueryReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.QueryReq)
  ))
_sym_db.RegisterMessage(QueryReq)

QueryResp = _reflection.GeneratedProtocolMessageType('QueryResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESP,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.QueryResp)
  ))
_sym_db.RegisterMessage(QueryResp)

ConfigReq = _reflection.GeneratedProtocolMessageType('ConfigReq', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigReq)
  ))
_sym_db.RegisterMessage(ConfigReq)

ConfigResp = _reflection.GeneratedProtocolMessageType('ConfigResp', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGRESP,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigResp)
  ))
_sym_db.RegisterMessage(ConfigResp)



_DA = _descriptor.ServiceDescriptor(
  name='da',
  full_name='DataAgent.da',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=143,
  serialized_end=327,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConfigInt',
    full_name='DataAgent.da.GetConfigInt',
    index=0,
    containing_service=None,
    input_type=_CONFIGINTREQ,
    output_type=_CONFIGINTRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Config',
    full_name='DataAgent.da.Config',
    index=1,
    containing_service=None,
    input_type=_CONFIGREQ,
    output_type=_CONFIGRESP,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='DataAgent.da.Query',
    index=2,
    containing_service=None,
    input_type=_QUERYREQ,
    output_type=_QUERYRESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DA)

DESCRIPTOR.services_by_name['da'] = _DA

# @@protoc_insertion_point(module_scope)
