// Code generated by protoc-gen-go. DO NOT EDIT.
// source: da.proto

package DataAgent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message for GetBlob
type BlobReq struct {
	ImgHandle            string   `protobuf:"bytes,1,opt,name=imgHandle" json:"imgHandle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobReq) Reset()         { *m = BlobReq{} }
func (m *BlobReq) String() string { return proto.CompactTextString(m) }
func (*BlobReq) ProtoMessage()    {}
func (*BlobReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{0}
}
func (m *BlobReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobReq.Unmarshal(m, b)
}
func (m *BlobReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobReq.Marshal(b, m, deterministic)
}
func (dst *BlobReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobReq.Merge(dst, src)
}
func (m *BlobReq) XXX_Size() int {
	return xxx_messageInfo_BlobReq.Size(m)
}
func (m *BlobReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlobReq proto.InternalMessageInfo

func (m *BlobReq) GetImgHandle() string {
	if m != nil {
		return m.ImgHandle
	}
	return ""
}

// Chunk message for GetBlob
type Chunk struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{1}
}
func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (dst *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(dst, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

// The request message for GetQuery
type QueryReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReq) Reset()         { *m = QueryReq{} }
func (m *QueryReq) String() string { return proto.CompactTextString(m) }
func (*QueryReq) ProtoMessage()    {}
func (*QueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{2}
}
func (m *QueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReq.Unmarshal(m, b)
}
func (m *QueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReq.Marshal(b, m, deterministic)
}
func (dst *QueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReq.Merge(dst, src)
}
func (m *QueryReq) XXX_Size() int {
	return xxx_messageInfo_QueryReq.Size(m)
}
func (m *QueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReq proto.InternalMessageInfo

// The response message for GetQuery
type QueryResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResp) Reset()         { *m = QueryResp{} }
func (m *QueryResp) String() string { return proto.CompactTextString(m) }
func (*QueryResp) ProtoMessage()    {}
func (*QueryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{3}
}
func (m *QueryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResp.Unmarshal(m, b)
}
func (m *QueryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResp.Marshal(b, m, deterministic)
}
func (dst *QueryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResp.Merge(dst, src)
}
func (m *QueryResp) XXX_Size() int {
	return xxx_messageInfo_QueryResp.Size(m)
}
func (m *QueryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResp proto.InternalMessageInfo

// The request message for GetConfig
type ConfigReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigReq) Reset()         { *m = ConfigReq{} }
func (m *ConfigReq) String() string { return proto.CompactTextString(m) }
func (*ConfigReq) ProtoMessage()    {}
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{4}
}
func (m *ConfigReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigReq.Unmarshal(m, b)
}
func (m *ConfigReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigReq.Marshal(b, m, deterministic)
}
func (dst *ConfigReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigReq.Merge(dst, src)
}
func (m *ConfigReq) XXX_Size() int {
	return xxx_messageInfo_ConfigReq.Size(m)
}
func (m *ConfigReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigReq proto.InternalMessageInfo

// The response message for GetConfig
type ConfigResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResp) Reset()         { *m = ConfigResp{} }
func (m *ConfigResp) String() string { return proto.CompactTextString(m) }
func (*ConfigResp) ProtoMessage()    {}
func (*ConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_da_a24fab982f9e18e5, []int{5}
}
func (m *ConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResp.Unmarshal(m, b)
}
func (m *ConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResp.Marshal(b, m, deterministic)
}
func (dst *ConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResp.Merge(dst, src)
}
func (m *ConfigResp) XXX_Size() int {
	return xxx_messageInfo_ConfigResp.Size(m)
}
func (m *ConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BlobReq)(nil), "DataAgent.BlobReq")
	proto.RegisterType((*Chunk)(nil), "DataAgent.Chunk")
	proto.RegisterType((*QueryReq)(nil), "DataAgent.QueryReq")
	proto.RegisterType((*QueryResp)(nil), "DataAgent.QueryResp")
	proto.RegisterType((*ConfigReq)(nil), "DataAgent.ConfigReq")
	proto.RegisterType((*ConfigResp)(nil), "DataAgent.ConfigResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaClient is the client API for Da service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaClient interface {
	// **********External Interfaces***************
	// GetConfig external interface
	Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error)
	// GetQuery external interface
	Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error)
	// GetBlob external interface
	GetBlob(ctx context.Context, in *BlobReq, opts ...grpc.CallOption) (Da_GetBlobClient, error)
}

type daClient struct {
	cc *grpc.ClientConn
}

func NewDaClient(cc *grpc.ClientConn) DaClient {
	return &daClient{cc}
}

func (c *daClient) Config(ctx context.Context, in *ConfigReq, opts ...grpc.CallOption) (*ConfigResp, error) {
	out := new(ConfigResp)
	err := c.cc.Invoke(ctx, "/DataAgent.da/Config", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daClient) Query(ctx context.Context, in *QueryReq, opts ...grpc.CallOption) (*QueryResp, error) {
	out := new(QueryResp)
	err := c.cc.Invoke(ctx, "/DataAgent.da/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daClient) GetBlob(ctx context.Context, in *BlobReq, opts ...grpc.CallOption) (Da_GetBlobClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Da_serviceDesc.Streams[0], "/DataAgent.da/GetBlob", opts...)
	if err != nil {
		return nil, err
	}
	x := &daGetBlobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Da_GetBlobClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type daGetBlobClient struct {
	grpc.ClientStream
}

func (x *daGetBlobClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DaServer is the server API for Da service.
type DaServer interface {
	// **********External Interfaces***************
	// GetConfig external interface
	Config(context.Context, *ConfigReq) (*ConfigResp, error)
	// GetQuery external interface
	Query(context.Context, *QueryReq) (*QueryResp, error)
	// GetBlob external interface
	GetBlob(*BlobReq, Da_GetBlobServer) error
}

func RegisterDaServer(s *grpc.Server, srv DaServer) {
	s.RegisterService(&_Da_serviceDesc, srv)
}

func _Da_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataAgent.da/Config",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaServer).Config(ctx, req.(*ConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Da_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataAgent.da/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaServer).Query(ctx, req.(*QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Da_GetBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlobReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaServer).GetBlob(m, &daGetBlobServer{stream})
}

type Da_GetBlobServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type daGetBlobServer struct {
	grpc.ServerStream
}

func (x *daGetBlobServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

var _Da_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataAgent.da",
	HandlerType: (*DaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _Da_Config_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Da_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlob",
			Handler:       _Da_GetBlob_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "da.proto",
}

func init() { proto.RegisterFile("da.proto", fileDescriptor_da_a24fab982f9e18e5) }

var fileDescriptor_da_a24fab982f9e18e5 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x74, 0x49, 0x2c, 0x49, 0x74, 0x4c, 0x4f, 0xcd, 0x2b, 0x51,
	0x52, 0xe7, 0x62, 0x77, 0xca, 0xc9, 0x4f, 0x0a, 0x4a, 0x2d, 0x14, 0x92, 0xe1, 0xe2, 0xcc, 0xcc,
	0x4d, 0xf7, 0x48, 0xcc, 0x4b, 0xc9, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08,
	0x28, 0xc9, 0x72, 0xb1, 0x3a, 0x67, 0x94, 0xe6, 0x65, 0x0b, 0x89, 0x70, 0xb1, 0x26, 0x83, 0x18,
	0x60, 0x25, 0x3c, 0x41, 0x10, 0x8e, 0x12, 0x17, 0x17, 0x47, 0x60, 0x69, 0x6a, 0x51, 0x65, 0x50,
	0x6a, 0xa1, 0x12, 0x37, 0x17, 0x27, 0x94, 0x5d, 0x5c, 0x00, 0xe2, 0x38, 0xe7, 0xe7, 0xa5, 0x65,
	0xa6, 0x83, 0x64, 0x78, 0xb8, 0xb8, 0x60, 0x9c, 0xe2, 0x02, 0xa3, 0x15, 0x8c, 0x5c, 0x4c, 0x29,
	0x89, 0x42, 0xe6, 0x5c, 0x6c, 0x10, 0x41, 0x21, 0x11, 0x3d, 0xb8, 0xc3, 0xf4, 0xe0, 0x9a, 0xa4,
	0x44, 0xb1, 0x88, 0x16, 0x17, 0x28, 0x31, 0x08, 0x99, 0x70, 0xb1, 0x82, 0xed, 0x11, 0x12, 0x46,
	0x52, 0x01, 0x73, 0x85, 0x94, 0x08, 0xa6, 0x20, 0x58, 0x97, 0x31, 0x17, 0xbb, 0x7b, 0x6a, 0x09,
	0xc8, 0xd3, 0x42, 0x42, 0x48, 0x4a, 0xa0, 0xa1, 0x20, 0x25, 0x80, 0x6c, 0x1b, 0xd8, 0x6b, 0x0c,
	0x06, 0x8c, 0x49, 0x6c, 0xe0, 0x80, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x13, 0x50, 0x32,
	0xe7, 0x44, 0x01, 0x00, 0x00,
}
