# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: da.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='da.proto',
  package='DataAgent',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08\x64\x61.proto\x12\tDataAgent\"\x1c\n\x07\x42lobReq\x12\x11\n\timgHandle\x18\x01 \x01(\t\"\x16\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\n\n\x08QueryReq\"\x0b\n\tQueryResp\"\x0b\n\tConfigReq\"\x0c\n\nConfigResp2\xa8\x01\n\x02\x64\x61\x12\x37\n\x06\x43onfig\x12\x14.DataAgent.ConfigReq\x1a\x15.DataAgent.ConfigResp\"\x00\x12\x34\n\x05Query\x12\x13.DataAgent.QueryReq\x1a\x14.DataAgent.QueryResp\"\x00\x12\x33\n\x07GetBlob\x12\x12.DataAgent.BlobReq\x1a\x10.DataAgent.Chunk\"\x00\x30\x01\x62\x06proto3')
)




_BLOBREQ = _descriptor.Descriptor(
  name='BlobReq',
  full_name='DataAgent.BlobReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imgHandle', full_name='DataAgent.BlobReq.imgHandle', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=51,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='DataAgent.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='DataAgent.Chunk.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=75,
)


_QUERYREQ = _descriptor.Descriptor(
  name='QueryReq',
  full_name='DataAgent.QueryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=87,
)


_QUERYRESP = _descriptor.Descriptor(
  name='QueryResp',
  full_name='DataAgent.QueryResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=100,
)


_CONFIGREQ = _descriptor.Descriptor(
  name='ConfigReq',
  full_name='DataAgent.ConfigReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=113,
)


_CONFIGRESP = _descriptor.Descriptor(
  name='ConfigResp',
  full_name='DataAgent.ConfigResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['BlobReq'] = _BLOBREQ
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['QueryReq'] = _QUERYREQ
DESCRIPTOR.message_types_by_name['QueryResp'] = _QUERYRESP
DESCRIPTOR.message_types_by_name['ConfigReq'] = _CONFIGREQ
DESCRIPTOR.message_types_by_name['ConfigResp'] = _CONFIGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlobReq = _reflection.GeneratedProtocolMessageType('BlobReq', (_message.Message,), dict(
  DESCRIPTOR = _BLOBREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.BlobReq)
  ))
_sym_db.RegisterMessage(BlobReq)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.Chunk)
  ))
_sym_db.RegisterMessage(Chunk)

QueryReq = _reflection.GeneratedProtocolMessageType('QueryReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.QueryReq)
  ))
_sym_db.RegisterMessage(QueryReq)

QueryResp = _reflection.GeneratedProtocolMessageType('QueryResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESP,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.QueryResp)
  ))
_sym_db.RegisterMessage(QueryResp)

ConfigReq = _reflection.GeneratedProtocolMessageType('ConfigReq', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGREQ,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigReq)
  ))
_sym_db.RegisterMessage(ConfigReq)

ConfigResp = _reflection.GeneratedProtocolMessageType('ConfigResp', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGRESP,
  __module__ = 'da_pb2'
  # @@protoc_insertion_point(class_scope:DataAgent.ConfigResp)
  ))
_sym_db.RegisterMessage(ConfigResp)



_DA = _descriptor.ServiceDescriptor(
  name='da',
  full_name='DataAgent.da',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='Config',
    full_name='DataAgent.da.Config',
    index=0,
    containing_service=None,
    input_type=_CONFIGREQ,
    output_type=_CONFIGRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='DataAgent.da.Query',
    index=1,
    containing_service=None,
    input_type=_QUERYREQ,
    output_type=_QUERYRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlob',
    full_name='DataAgent.da.GetBlob',
    index=2,
    containing_service=None,
    input_type=_BLOBREQ,
    output_type=_CHUNK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DA)

DESCRIPTOR.services_by_name['da'] = _DA

# @@protoc_insertion_point(module_scope)
