version: '3'
services:
  # Define DataAgent service - hosts vault daemon, influxdb daemon & DataAgent module
  ia_data_agent:
    volumes:
      - "${IEI_INSTALL_PATH}/config/provision_config.json:/IEI/go/src/IEdgeInsights/DataAgent/provision_config.json"
  
  ia_data_analytics:
    environment:
      KAPACITOR_URL: http://${KAPACITOR_SERVER}:${KAPACITOR_PORT}/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://${INFLUX_SERVER}:${INFLUXDB_PORT}/

  ia_video_ingestion:
    volumes:
      - "${IEI_INSTALL_PATH}/filters:/IEI/VideoIngestion/filters"

  ia_video_analytics:
    volumes:
      - "${IEI_INSTALL_PATH}/classifiers:/IEI/VideoAnalytics/classifiers"
