version: '3'

services:

  #----Start: IEI Base Images----
  # Define ia_gobase service
  ia_gobase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gobase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          HOST_TIME_ZONE: ${HOST_TIME_ZONE}
    image: ia_gobase:${IEI_VERSION}

  # Define ia_pybase service
  ia_pybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.pybase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          IEI_VERSION: ${IEI_VERSION}
    image: ia_pybase:${IEI_VERSION}

  # Define ia_gopybase service
  ia_gopybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gopybase
      args:
        IEI_VERSION: ${IEI_VERSION}
    image: ia_gopybase:${IEI_VERSION}

  #----End: IEI Base Images----

  #----Start: IEI Containers ----
  # Define telegraf service
  ia_telegraf:
    build:
      context: ../
      dockerfile: $PWD/../Telegraf/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    container_name: ia_telegraf
    hostname: ia_telegraf
    network_mode: host
    image: ia_telegraf:${IEI_VERSION}
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      SHARED_KEY: ${SHARED_KEY}
      SHARED_NONCE: ${SHARED_NONCE}
      INFLUX_SERVER: ${INFLUX_SERVER}
      INFLUXDB_PORT: ${INFLUXDB_PORT}
      no_proxy: ${NO_PROXY}
      DEV_MODE: ${DEV_MODE}
      HOST_IP: ${HOST_IP}
      DATA_AGENT_GRPC_SERVER: ${DATA_AGENT_GRPC_SERVER}
    volumes:
      - "${IEI_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${IEI_INSTALL_PATH}/config/telegraf.conf:/etc/Telegraf/telegraf.conf"
      - "${IEI_INSTALL_PATH}/config/telegraf_devmode.conf:/etc/Telegraf/telegraf_devmode.conf"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
       test: ["CMD-SHELL", "exit", "0"]
       interval: ${HEALTHCHECK_DURATION}
    user: ${IEI_UID}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges


  # Define Imagestore service which hosts redis and minio dbs
  ia_imagestore:
    build:
      context: ../
      dockerfile: $PWD/../ImageStore/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        REDIS_VERSION: ${REDIS_VERSION}
        MINIO_VERSION: ${MINIO_VERSION}
        IEI_UID: ${IEI_UID}
    container_name: ia_imagestore
    hostname: ia_imagestore
    network_mode: host
    image: ia_imagestore:${IEI_VERSION}
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      no_proxy: ${NO_PROXY}
      DEV_MODE: ${DEV_MODE}
      SHARED_KEY: ${SHARED_KEY}
      SHARED_NONCE: ${SHARED_NONCE}
      REDIS_PORT: ${REDIS_PORT}
      MINIO_PORT: ${MINIO_PORT}
      DATA_AGENT_GRPC_SERVER: ${DATA_AGENT_GRPC_SERVER}
      INFLUX_SERVER: ${INFLUX_SERVER}
      IMAGESTORE_GRPC_SERVER: ${IMAGESTORE_GRPC_SERVER}
      GRPC_INTERNAL_PORT: ${GRPC_INTERNAL_PORT}
      IMAGESTORE_PORT: ${IMAGESTORE_PORT}
      GO_LOG_LEVEL: ${GO_LOG_LEVEL}
      GO_VERBOSE: ${GO_VERBOSE}
    command: ["-log_dir", "/IEI/go/src/IEdgeInsights/log/imagestore_logs", "-stderrthreshold", "${GO_LOG_LEVEL}", "-v", "${GO_VERBOSE}"]
    ports:
      - "${IMAGESTORE_PORT}:${IMAGESTORE_PORT}"
    volumes:
      - "${IEI_INSTALL_PATH}/data:/data"
      - "${IEI_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    user: ${IEI_UID}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges

  # Define DataAnalytics service
  ia_data_analytics:
    build:
      context: ../
      dockerfile: $PWD/../DataAnalytics/PointDataAnalytics/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    image: ia_data_analytics:${IEI_VERSION}
    container_name: ia_data_analytics
    hostname: ia_data_analytics
    network_mode: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      SHARED_KEY: ${SHARED_KEY}
      SHARED_NONCE: ${SHARED_NONCE}
      KAPACITOR_URL: https://${KAPACITOR_SERVER}:${KAPACITOR_PORT}/
      KAPACITOR_UNSAFE_SSL: "false"
      KAPACITOR_INFLUXDB_0_URLS_0: https://${KAPACITOR_SERVER}:${INFLUXDB_PORT}/
      KAPACITOR_SERVER: ${KAPACITOR_SERVER}
      INFLUX_SERVER: ${INFLUX_SERVER}
      DATA_AGENT_GRPC_SERVER: ${DATA_AGENT_GRPC_SERVER}
      IMAGESTORE_GRPC_SERVER: ${IMAGESTORE_GRPC_SERVER}
      GRPC_INTERNAL_PORT: ${GRPC_INTERNAL_PORT}
      no_proxy: ${NO_PROXY}
      KAPACITOR_PORT: ${KAPACITOR_PORT}
      INFLUXDB_PORT: ${INFLUXDB_PORT}
      PY_LOG_LEVEL: ${PY_LOG_LEVEL}
    volumes:
      - "${IEI_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${IEI_INSTALL_PATH}/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf"
      - "${IEI_INSTALL_PATH}/config/kapacitor_devmode.conf:/etc/kapacitor/kapacitor_devmode.conf"
    ports:
      - "${KAPACITOR_PORT}:${KAPACITOR_PORT}"
    command: ["${CONFIG_FILE}", "${PY_LOG_LEVEL}", "${DEV_MODE}"]
    devices:
      - "/dev/dri"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    user: ${IEI_UID}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges

  # Define VideoAnalytics service
  ia_video_analytics:
    build:
      context: ../
      dockerfile: $PWD/../DataAnalytics/VideoAnalytics/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    image: ia_video_analytics:${IEI_VERSION}
    container_name: ia_video_analytics
    hostname: ia_video_analytics
    network_mode: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      AppName: "VideoAnalytics"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${NO_PROXY}
      PY_LOG_LEVEL: ${PY_LOG_LEVEL}
      PROFILING: ${PROFILING}
      SubTopics: "camera1_stream"
      camera1_stream_cfg : "ZeroMQ/TCP,127.0.0.1:65011"
      PubTopics: "camera1_stream_results"
      camera1_stream_results_cfg : "ZeroMQ/TCP,127.0.0.1:65013"
    privileged: true
    volumes:
      - "/dev:/dev"
    devices:
      - "/dev/dri"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges


  # Define FactoryControlApp service
  ia_factoryctrl_app:
    build:
      context: ../
      dockerfile: $PWD/../FactoryControlApp/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    image: ia_factoryctrl_app:${IEI_VERSION}
    container_name: ia_factoryctrl_app
    hostname: ia_factoryctrl_app
    network_mode: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      SHARED_KEY: ${SHARED_KEY}
      SHARED_NONCE: ${SHARED_NONCE}
      INFLUX_SERVER: ${INFLUX_SERVER}
      DATA_AGENT_GRPC_SERVER: ${DATA_AGENT_GRPC_SERVER}
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${NO_PROXY}
    volumes:
      - "${IEI_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
    command: ["--log", "${PY_LOG_LEVEL}"]
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    user: ${IEI_UID}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges

  # Define VideoIngestion service
  ia_video_ingestion:
    build:
      context: ../
      dockerfile: $PWD/../VideoIngestion/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    image: ia_video_ingestion:${IEI_VERSION}
    container_name: ia_video_ingestion
    hostname: ia_video_ingestion
    network_mode: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      AppName: "VideoIngestion"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${NO_PROXY},${RTSP_CAMERA_IP}
      DEBIAN_FRONTEND: noninteractive
      MFX_HOME: "/opt/intel/mediasdk/"
      PKG_CONFIG_PATH: "/opt/intel/mediasdk"
      LIBVA_DRIVERS_PATH: "/usr/lib/x86_64-linux-gnu/dri/"
      LIBVA_DRIVER_NAME: "iHD"
      LD_RUN_PATH: "/usr/lib"
      LD_LIBRARY_PATH: "/opt/intel/mediasdk/lib/:/opt/intel/mediasdk/share/mfx/samples"
      TERM: "xterm"
      GST_PLUGIN_PATH: "/usr/local/lib/gstreamer-1.0"
      GST_DEBUG: ${GST_DEBUG}
      PROFILING: ${PROFILING}
      PubTopics: "camera1_stream"
      camera1_stream_cfg: "ZeroMQ/TCP,127.0.0.1:65011"
    volumes:
      - "${IEI_INSTALL_PATH}/test_videos:/IEI/test_videos"
    command: ["--log-dir", "/IEI/video_ingestion_logs", "--log", "${PY_LOG_LEVEL}"]
    privileged: true
    devices:
      - "/dev/dri"
      - "/dev/:/dev/"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    user: ${IEI_UID}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges

  ia_visualizer:
    build:
      context: ../
      dockerfile: $PWD/../tools/visualizer/Dockerfile
      args:
        IEI_VERSION: ${IEI_VERSION}
        IEI_UID: ${IEI_UID}
    image: ia_visualizer:${IEI_VERSION}
    container_name: ia_visualizer
    hostname: ia_visualizer
    network_mode: host
    ipc: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      no_proxy: ${NO_PROXY}
      PY_LOG_LEVEL: ${PY_LOG_LEVEL}
      DISPLAY: ${DISPLAY}
      SubTopics: "camera1_stream_results"
      camera1_stream_results_cfg : "ZeroMQ/TCP,127.0.0.1:65013"
    privileged: true
    volumes:
      - "${IEI_INSTALL_PATH}/saved_images:${IEI_INSTALL_PATH}/saved_images"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
    security_opt:
      - seccomp:$PWD/config/seccomp_default.json
      - no-new-privileges

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}

  #----End: IEI Containers ----
