version: '3'

services:
  
  #---- Start: ETA Dependency Services----
  # Define an InfluxDB service
  influxdb:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.influxdb
    container_name: influxdb
    hostname: influxdb
    volumes:
      - /var/lib/eta/config/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
      
  # Define an Redis service
  redis:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.redis
    container_name: redis
    hostname: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  #---- End: ETA Dependency Services----
  
  #----Start: ETA Base Images----
  # Define ia-gobase service
  ia-gobase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gobase
    image: ia/gobase:1.0

  # Define ia-pybase service
  ia-pybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.pybase
    image: ia/pybase:1.0

  # Define ia-gopybase service
  ia-gopybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gopybase
    image: ia/gopybase:1.0
  
  #----End: ETA Base Images----
  
  #----Start: ETA Containers ----
  # Define DataAgent service
  ia_data_agent:
    depends_on:
      - ia-gobase
      - influxdb
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.da
    image: ia/data_agent:1.0
    container_name: ia_data_agent
    hostname: ia_data_agent
    volumes:
      - /var/lib/eta/config/DataAgent.conf:/root/go/src/ElephantTrunkArch/DataAgent/DataAgent.conf
      - /var/lib/eta/logs/DataAgent:/ETA/log/DataAgent
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${OPCUA_PORT}:${OPCUA_PORT}"
        
  # Define DataAnalytics service
  ia_data_analytics:
    depends_on:
      - influxdb
      - redis
      - ia_data_agent
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.classifier
    image: ia/data_analytics:1.0
    container_name: ia_data_analytics
    hostname: ia_data_analytics
    environment:
      KAPACITOR_HOSTNAME: ia_data_analytics
      KAPACITOR_URL: http://ia_data_analytics:9092/
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086/
      GRPC_SERVER: ${GRPC_SERVER_HOST}
    volumes:
      - /var/lib/eta/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - /var/lib/eta/config/factory.json:/ETA/factory.json
      - /var/lib/eta/config/factory_cam.json:/ETA/factory_cam.json
      - /var/lib/eta/classifier_logs:/ETA/classifier_logs
    command: ${CONFIG_FILE}
    expose:
      - "9092"

  # Define VideoIngestion service
  ia_video_ingestion:
    depends_on:
      - influxdb
      - redis
      - ia_data_analytics
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.vi
    image: ia/video_ingestion:1.0
    container_name: ia_video_ingestion
    hostname: ia_video_ingestion
    network_mode: host
    volumes:
      - /var/lib/eta/test_videos:/ETA/test_videos
      - /var/lib/eta/config/factory.json:/ETA/factory.json
      - /var/lib/eta/config/factory_cam.json:/ETA/factory_cam.json
      - /var/lib/eta/logs/video_ingestion_logs:/ETA/video_ingestion_logs
    command: ${CONFIG_FILE}
   
  #----End: ETA Containers ----
