version: '3'

services:

  #---- Start: ETA Dependency Services----
  # Define a log_rotate service
  ia_log_rotate:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.logrotate
      args:
        LOG_ROTATE_VERSION: ${LOG_ROTATE_VERSION}
    container_name: ia_log_rotate
    hostname: ia_log_rotate
    image: ia/logrotate:${ETA_VERSION}
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      LOGS_DIRECTORIES: ${ETA_INSTALL_PATH}/logs
      # Logrotate can rotate logfile according to the following intervals:
      # hourly
      # daily
      # weekly
      # monthly
      # yearly
      # For more details, refer the following link
      # https://hub.docker.com/r/blacklabelops/logrotate/
      LOGROTATE_INTERVAL: "daily"
      LOGROTATE_COPIES: ${LOGROTATE_COPIES}
      LOGROTATE_DATEFORMAT: "%Y%m%d_%H:%M:%S"
      TZ: ${HOST_TIME_ZONE}
    volumes:
      - "${ETA_INSTALL_PATH}/logs:${ETA_INSTALL_PATH}/logs"
    healthcheck:
       test: ["CMD-SHELL", "exit", "0"]
       interval: ${HEALTHCHECK_DURATION}

  #---- End: ETA Dependency Services----

  #----Start: ETA Base Images----
  # Define ia-gobase service
  ia-gobase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gobase
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
    image: ia/gobase:${ETA_VERSION}
    depends_on:
      - ia_log_rotate

  # Define ia-pybase service
  ia-pybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.pybase
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
    image: ia/pybase:${ETA_VERSION}
    depends_on:
      - ia_log_rotate

  # Define ia-gopybase service
  ia-gopybase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gopybase
      args:
        ETA_VERSION: ${ETA_VERSION}
    image: ia/gopybase:${ETA_VERSION}
    depends_on:
      - ia_log_rotate

  #----End: ETA Base Images----

  #----Start: ETA Containers ----
  # Define DataAgent service - hosts vault daemon, influxdb daemon & DataAgent module
  ia_data_agent:
    links:
      - ia_log_rotate
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.da
      args:
        ETA_VERSION: ${ETA_VERSION}
        INFLUXDB_VERSION: ${INFLUXDB_VERSION}
    image: ia/data_agent:${ETA_VERSION}
    container_name: ia_data_agent
    hostname: ia_data_agent
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${NO_PROXY}
      IMAGESTORE_SERVER: ${IMAGESTORE_SERVER_HOST}
      INFLUX_SERVER: ${INFLUX_SERVER_HOST}
      GRPC_INTERNAL_PORT: ${GRPC_INTERNAL_PORT}
      GRPC_EXTERNAL_PORT: ${GRPC_EXTERNAL_PORT}
      INFLUXDB_HTTP_AUTH_ENABLED: ${INFLUX_AUTH_VALUE}
    volumes:
      - "${CERTIFICATES_PATH}:/etc/ssl"
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${ETA_INSTALL_PATH}/config/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "${ETA_INSTALL_PATH}/secret_store:/vault/file"
      - "${ETA_INSTALL_PATH}/vault_secret_file:/root/go/src/ElephantTrunkArch/DataAgent/vault_secret_file"
    ports:
      - "${GRPC_INTERNAL_PORT}:${GRPC_INTERNAL_PORT}"
      - "${OPCUA_PORT}:${OPCUA_PORT}"
      - "${INFLUXDB_PORT}:${INFLUXDB_PORT}"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}

  # Define telegraf service
  ia_telegraf:
    links:
      - ia_data_agent:ia_influxdb
    external_links:
      - ia_mqtt
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.telegraf
      args:
        ETA_VERSION: ${ETA_VERSION}
    container_name: ia_telegraf
    hostname: ia_telegraf
    image: ia/telegraf:${ETA_VERSION}
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      INFLUX_SERVER: ${INFLUX_SERVER_HOST}
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${NO_PROXY}
      GRPC_SERVER: ${GRPC_SERVER_HOST}
      HOST_IP: ${HOST_IP}
    volumes:
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${ETA_INSTALL_PATH}/config/telegraf.conf:/root/go/src/ElephantTrunkArch/Telegraf/Telegraf.conf"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
       test: ["CMD-SHELL", "exit", "0"]
       interval: ${HEALTHCHECK_DURATION}


  # Define Imagestore service which hosts redis and minio dbs
  ia_imagestore:
    links:
       - ia_data_agent
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.imagestore
      args:
        ETA_VERSION: ${ETA_VERSION}
    container_name: ia_imagestore
    hostname: ia_imagestore
    image: ia/imagestore:${ETA_VERSION}
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${NO_PROXY}
      REDIS_PORT: ${REDIS_PORT}
      MINIO_PORT: ${MINIO_PORT}
      GRPC_SERVER: ${GRPC_SERVER_HOST}  
    ports:
      - "${IMAGESTORE_PORT}:${IMAGESTORE_PORT}"
    volumes:
      - "${ETA_INSTALL_PATH}/data:/data"
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${CERTIFICATES_PATH}/imagestore:/etc/ssl/imagestore"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}

  # Define DataAnalytics service
  ia_data_analytics:
    links:
      - ia_data_agent:ia_influxdb
      - ia_imagestore
    external_links:
       -  ia_mqtt
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.classifier
      args:
        ETA_VERSION: ${ETA_VERSION}
    image: ia/data_analytics:${ETA_VERSION}
    container_name: ia_data_analytics
    hostname: ia_data_analytics
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      KAPACITOR_HOSTNAME: ia_data_analytics
      KAPACITOR_URL: https://ia_data_analytics:${KAPACITOR_PORT}/
      KAPACITOR_UNSAFE_SSL: "false"
      KAPACITOR_INFLUXDB_0_URLS_0: https://ia_influxdb:${INFLUXDB_PORT}/
      INFLUX_SERVER: ${INFLUX_SERVER_HOST}
      GRPC_SERVER: ${GRPC_SERVER_HOST}
      IMAGESTORE_SERVER: ${IMAGESTORE_SERVER_HOST}
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${NO_PROXY}
      KAPACITOR_PORT: ${KAPACITOR_PORT}
      INFLUXDB_PORT: ${INFLUXDB_PORT}
    volumes:
      - "${CERTIFICATES_PATH}/influxdb:/etc/ssl/influxdb"
      - "${CERTIFICATES_PATH}/kapacitor:/etc/ssl/kapacitor"
      - "${CERTIFICATES_PATH}/imagestore:/etc/ssl/imagestore"
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${ETA_INSTALL_PATH}/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf"
      - "${ETA_INSTALL_PATH}/config/factory.json:/ETA/factory.json"
      - "${ETA_INSTALL_PATH}/config/factory_prod.json:/ETA/factory_prod.json"
      - "${ETA_INSTALL_PATH}/config/ref:/ETA/agent/ref"
      - "${ETA_INSTALL_PATH}/config/ref_prod:/ETA/agent/ref_prod"
      - "${ETA_INSTALL_PATH}/logs/classifier_logs:/ETA/classifier_logs"
    expose:
      - ${KAPACITOR_PORT}
    command: ["--config", "${CONFIG_FILE}", "--log", "${LOG_LEVEL}"]
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}

  # Define YumeiApp service
  ia_yumei_app:
    links:
       - ia_data_analytics
       - ia_data_agent:ia_influxdb
    external_links:
       - ia_mqtt
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.yumeiapp
      args:
        ETA_VERSION: ${ETA_VERSION}
    image: ia/yumei_app:${ETA_VERSION}
    container_name: ia_yumei_app
    hostname: ia_yumei_app
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      INFLUX_SERVER: ${INFLUX_SERVER_HOST}
      GRPC_SERVER: ${GRPC_SERVER_HOST}
      NO_PROXY: ${NO_PROXY},${HOST_IP}
      no_proxy: ${NO_PROXY},${HOST_IP}
    volumes:
      - "${CERTIFICATES_PATH}/streamsublib:/etc/ssl/streamsublib"
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${ETA_INSTALL_PATH}/logs/yumei_app_logs:/ETA/yumei_app_logs"
    command: ["--log", "${LOG_LEVEL}"]
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}

  # Define VideoIngestion service
  ia_video_ingestion:
    depends_on:
      - ia_imagestore
      - ia_data_analytics
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.vi
      args:
        ETA_VERSION: ${ETA_VERSION}
    image: ia/video_ingestion:${ETA_VERSION}
    container_name: ia_video_ingestion
    hostname: ia_video_ingestion
    network_mode: host
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      INFLUX_SERVER: "localhost"
      IMAGESTORE_SERVER: "localhost"
      GRPC_SERVER: "localhost"
      NO_PROXY: ${NO_PROXY},${HOST_IP},${RTSP_CAMERA_IP}
      no_proxy: ${NO_PROXY},${HOST_IP},${RTSP_CAMERA_IP}
      DEBIAN_FRONTEND: noninteractive
      MFX_HOME: "/opt/intel/mediasdk/"
      PKG_CONFIG_PATH: "/opt/intel/mediasdk"
      LIBVA_DRIVERS_PATH: "/usr/lib/x86_64-linux-gnu/dri/"
      LIBVA_DRIVER_NAME: "iHD"
      LD_RUN_PATH: "/usr/lib"
      LD_LIBRARY_PATH: "/opt/intel/mediasdk/lib/:/opt/intel/mediasdk/share/mfx/samples"
      TERM: "xterm"
    volumes:
      - "${CERTIFICATES_PATH}/imagestore:/etc/ssl/imagestore"
      - "${ETA_INSTALL_PATH}/grpc_int_ssl_secrets:/etc/ssl/grpc_int_ssl_secrets"
      - "${ETA_INSTALL_PATH}/test_videos:/ETA/test_videos"
      - "${ETA_INSTALL_PATH}/config/factory.json:/ETA/factory.json"
      - "${ETA_INSTALL_PATH}/config/factory_prod.json:/ETA/factory_prod.json"
      - "${ETA_INSTALL_PATH}/config/ref:/ETA/agent/ref"
      - "${ETA_INSTALL_PATH}/config/ref_prod:/ETA/agent/ref_prod"
      - "${ETA_INSTALL_PATH}/logs/video_ingestion_logs:/ETA/video_ingestion_logs"
    command: ["--config", "${CONFIG_FILE}", "--log", "${LOG_LEVEL}"]
    devices:
      - "/dev/dri"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}


networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}

  #----End: ETA Containers ----
