version: '3'
services:
  ia_data_analytics:
    environment:
      KAPACITOR_URL: http://${KAPACITOR_SERVER}:${KAPACITOR_PORT}/
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: http://${INFLUX_SERVER}:${INFLUXDB_PORT}/
