version: '3'

services:

  #----Start: ETA Base Images----
  # Define ia-gobase service
  ia-gobase:
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.gobase
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
    image: ia/gobase:${ETA_VERSION}

  #----End: ETA Base Images----

  ia_provision:
    depends_on:
      - ia-gobase
    build:
      context: ../
      dockerfile: $PWD/dockerfiles/Dockerfile.provision
      args:
        ETA_VERSION: ${ETA_VERSION}
    image: ia/provision:${ETA_VERSION}
    container_name: ia_provision
    hostname: ia_provision
    restart: on-failure:${FAILURE_ATTEMPTS}
    environment:
      NO_PROXY: ${NO_PROXY}
      no_proxy: ${NO_PROXY}
      VAULT_PORT: ${VAULT_PORT}
      TPM_ENABLE: ${TPM_ENABLE}
      LD_LIBRARY_PATH: /usr/local/lib
    volumes:
      - "${CERTIFICATES_PATH}:/etc/ssl"
      - "${ETA_INSTALL_PATH}/secret_store:/vault/file"
      - "${ETA_INSTALL_PATH}/tpm_secret:/ETA/tpm_secret"
    logging:
      driver: ${LOGGING_DRIVER}
      options:
        max-size: ${LOGROTATE_SIZE_FOR_CONT}
        max-file: ${LOGROTATE_COPIES}
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: ${HEALTHCHECK_DURATION}
        

  #----End: ETA Containers ----
